"""Acholi (Luo) - English Dictionary
Comprehensive word list for translation
"""

ACHOLI_DICT = {
    # ============================================
    # GREETINGS & PLEASANTRIES
    # ============================================
    "good morning": "Itye odyo",
    "good afternoon": "Itye odyo",
    "good evening": "Itye odyo",
    "good night": "Onyen ninde",
    "hello": "Itye",
    "hi": "Itye",
    "hey": "Itye",
    "how are you": "Itye nining",
    "how are you?": "Itye nining",
    "i am fine": "Atye maber",
    "i'm fine": "Atye maber",
    "i am okay": "Atye maber",
    "nice to meet you": "Amito nyara",
    "welcome": "Ibinongo",
    "goodbye": "Oriti",
    "bye": "Oriti",
    "see you later": "Wunen aye",
    "see you tomorrow": "Wunen kinyen",
    "take care": "Iriyo maber",
    "thank you": "Apwoyo",
    "thanks": "Apwoyo",
    "thank you very much": "Apwoyo matek",
    "thanks a lot": "Apwoyo matek",
    "you're welcome": "Oyot",
    "please": "Miya",
    "sorry": "Tim kica",
    "excuse me": "Tim kica",
    "no problem": "Pe tye peko",
    "congratulations": "Bedo maber",
    "good luck": "Nyeku maber",

    # ============================================
    # BASIC YES/NO
    # ============================================
    "yes": "Eyo",
    "no": "Pe",
    "maybe": "Mogo",
    "okay": "Maber",
    "ok": "Maber",
    "alright": "Maber",
    "sure": "Adada",
    "i don't know": "Angeyo pe",
    "i know": "Angeyo",
    "i agree": "Ayie",
    "i disagree": "Ayie pe",
    "correct": "Adyera",
    "wrong": "Rac",
    "true": "Adada",
    "false": "Lok",

    # ============================================
    # QUESTION WORDS
    # ============================================
    "what": "Ngo",
    "what is this": "Man ngo",
    "what is that": "Mane ngo",
    "who": "Nga",
    "who are you": "In nga",
    "where": "Kwene",
    "where are you": "In kwene",
    "where are you going": "Itye kwene",
    "when": "Dano",
    "why": "Pingo",
    "how": "Nining",
    "how much": "Adi",
    "how many": "Adi",
    "which": "Mene",

    # ============================================
    # PERSONAL PRONOUNS
    # ============================================
    "i": "An",
    "me": "An",
    "you": "In",
    "he": "En",
    "she": "En",
    "it": "En",
    "we": "Wan",
    "us": "Wan",
    "they": "Gin",
    "them": "Gin",
    "my": "Mara",
    "your": "Mari",
    "his": "Mare",
    "her": "Mare",
    "our": "Mwa",
    "their": "Ma gin",

    # ============================================
    # FAMILY
    # ============================================
    "man": "Laco",
    "woman": "Dako",
    "boy": "Latin",
    "girl": "Nyako",
    "child": "Latin",
    "children": "Litino",
    "baby": "Latin manyen",
    "father": "Won",
    "mother": "Min",
    "son": "Wod",
    "daughter": "Nyare",
    "brother": "Omegi",
    "sister": "Omeru",
    "family": "Kaka",
    "friend": "Lakwena",
    "friends": "Lukwena",
    "neighbor": "Jamin",
    "teacher": "Lapwony",
    "student": "Lapwonnye",
    "doctor": "Ladwara",
    "nurse": "Lakony",
    "police": "Polis",
    "soldier": "Askeri",
    "driver": "Ladrii",
    "farmer": "Lapuru",
    "trader": "Lacat",
    "god": "Lubanga",

    # ============================================
    # NUMBERS
    # ============================================
    "one": "Acel",
    "two": "Aryo",
    "three": "Adok",
    "four": "Angwen",
    "five": "Abic",
    "six": "Abicel",
    "seven": "Abiriyo",
    "eight": "Aboro",
    "nine": "Abongwen",
    "ten": "Apye",
    "twenty": "Apye aryo",
    "thirty": "Apye adek",
    "forty": "Apye angwen",
    "fifty": "Apye abic",
    "hundred": "Mia",
    "thousand": "Aluf",
    "million": "Milion",

    # ============================================
    # TIME & DAYS
    # ============================================
    "today": "Tin",
    "yesterday": "Lacen",
    "tomorrow": "Kinyen",
    "now": "Kombedi",
    "later": "Itye lakini",
    "soon": "Cokki",
    "morning": "Odiko",
    "afternoon": "Otiko",
    "evening": "Otyeno",
    "night": "Wor",
    "day": "Nino",
    "week": "Cawa",
    "month": "Dwe",
    "year": "Maka",
    "time": "Cawa",
    "monday": "Bicel",
    "tuesday": "Bariyo",
    "wednesday": "Baradek",
    "thursday": "Barangwen",
    "friday": "Barabich",
    "saturday": "Bicel",
    "sunday": "Cabbit",

    # ============================================
    # FOOD & DRINK
    # ============================================
    "food": "Kec",
    "water": "Pi",
    "milk": "Cak",
    "tea": "Caai",
    "coffee": "Kawa",
    "juice": "Jusi",
    "beer": "Kongo",
    "bread": "Mugati",
    "rice": "Ocere",
    "beans": "Ogwal",
    "meat": "Ring",
    "chicken": "Gweno",
    "beef": "Ring romo",
    "goat": "Dyell",
    "fish": "Rec",
    "egg": "Toŋ",
    "fruit": "Yat",
    "banana": "Bok",
    "mango": "Muyembe",
    "orange": "Cungwa",
    "tomato": "Nyanya",
    "onion": "Tungulu",
    "potato": "Layata",
    "cassava": "Mogo",
    "maize": "Kadunde",
    "salt": "Cumb",
    "sugar": "Sukari",
    "oil": "Moo",
    "hungry": "Kec",
    "i am hungry": "Kec neka",
    "thirsty": "Pii",
    "i am thirsty": "Pii neka",
    "delicious": "Yot",
    "i am eating": "Atye caamo",
    "i want to eat": "Amito camo",

    # ============================================
    # BODY PARTS
    # ============================================
    "head": "Wic",
    "eye": "Wang",
    "eyes": "Wenge",
    "ear": "It",
    "nose": "Umer",
    "mouth": "Dogi",
    "tooth": "Lak",
    "teeth": "Lek",
    "tongue": "Leb",
    "neck": "Ngut",
    "shoulder": "Kom",
    "arm": "Cing",
    "hand": "Cing",
    "finger": "Lwet",
    "chest": "Koma",
    "stomach": "Ic",
    "back": "Ngut",
    "leg": "Tiel",
    "foot": "Tiel",
    "heart": "Cuny",
    "blood": "Remo",
    "bone": "Cogo",
    "skin": "Nyim",
    "hair": "Yie wic",
    "sick": "Two",
    "i am sick": "Two neka",
    "pain": "Rem",
    "hospital": "Odwara",
    "medicine": "Yat",
    "health": "Kwo",
    "life": "Kwo",
    "death": "To",
    "tired": "Ool",
    "i am tired": "Ool neka",
    "sleep": "Nino",
    "i want to sleep": "Amito nino",

    # ============================================
    # PLACES & DIRECTIONS
    # ============================================
    "home": "Gang",
    "house": "Ot",
    "school": "Skul",
    "church": "Mungu ot",
    "market": "Cok",
    "shop": "Dukka",
    "bank": "Banka",
    "road": "Yo",
    "street": "Yo",
    "city": "Dol",
    "village": "Gang",
    "country": "Piny",
    "world": "Piny",
    "place": "Kabedo",
    "here": "Kae",
    "there": "Kuca",
    "near": "Cok",
    "far": "Bor",
    "north": "Maleng",
    "south": "Marom",
    "east": "Wuok ceng",
    "west": "Podho ceng",
    "up": "Mal",
    "down": "Piny",
    "inside": "Iyie",
    "outside": "Woko",
    "where is the bathroom": "Kwene kwan",
    "where is the market": "Cok tye kwene",
    "i am lost": "An lal",
    "i am going home": "Atye dok gang",
    "i am going to the market": "Atye cok",

    # ============================================
    # VERBS
    # ============================================
    "go": "Wot",
    "come": "Bin",
    "eat": "Cam",
    "drink": "Mate",
    "sleep": "Nino",
    "wake up": "Cak",
    "walk": "Wot",
    "run": "Ring",
    "sit": "Bed",
    "stand": "Cung",
    "see": "Nen",
    "look": "Nen",
    "hear": "Winj",
    "listen": "Winj",
    "speak": "Lok",
    "talk": "Lok",
    "say": "Lok",
    "tell": "Tito",
    "ask": "Penj",
    "answer": "Gamo",
    "give": "Mi",
    "take": "Ter",
    "bring": "Kel",
    "send": "Cwal",
    "buy": "Ngwet",
    "sell": "Yar",
    "pay": "Cu",
    "work": "Tic",
    "play": "Tuk",
    "read": "Kwano",
    "write": "Coyo",
    "learn": "Pwonnye",
    "teach": "Pwonnyo",
    "help": "Kony",
    "help me": "Konya",
    "wait": "Kur",
    "stop": "Tok",
    "start": "Cak",
    "finish": "Ek",
    "open": "Yab",
    "close": "Lor",
    "enter": "Donjo",
    "exit": "Wot woko",
    "know": "Ngeyo",
    "understand": "Ngeyo",
    "i don't understand": "Angeyo pe",
    "think": "Paro",
    "want": "Mito",
    "i want": "Amito",
    "i don't want": "Amito pe",
    "need": "Mito",
    "love": "Mara",
    "i love you": "Amari",
    "like": "Mito",
    "hate": "Keco",
    "laugh": "Nyero",
    "cry": "Ywak",
    "sing": "Wero",
    "dance": "Yelo",
    "pray": "Lamo",

    # ============================================
    # ADJECTIVES
    # ============================================
    "good": "Maber",
    "very good": "Maber matek",
    "bad": "Rac",
    "very bad": "Rac matek",
    "big": "Dit",
    "small": "Tidi",
    "long": "Bor",
    "short": "Cok",
    "tall": "Bor",
    "new": "Manyen",
    "old": "Moto",
    "young": "Nyen",
    "hot": "Lyer",
    "cold": "Ngic",
    "warm": "Lyer",
    "fast": "Nyap",
    "slow": "Molo",
    "easy": "Yot",
    "difficult": "Tedo",
    "beautiful": "Ber",
    "ugly": "Rac",
    "rich": "Lonyo",
    "poor": "Can",
    "happy": "Yom",
    "sad": "Kumu",
    "angry": "Kiniga",
    "afraid": "Lworo",
    "strong": "Tek",
    "weak": "Goro",
    "clean": "Leng",
    "dirty": "Cido",
    "full": "Pong",
    "empty": "Non",
    "important": "Pire tek",
    "possible": "Twero",
    "impossible": "Pe twero",

    # ============================================
    # COLORS
    # ============================================
    "color": "Lang",
    "red": "Kwar",
    "blue": "Bul",
    "green": "Ceng",
    "yellow": "Yelo",
    "black": "Col",
    "white": "Tar",
    "orange": "Cungwa",
    "brown": "Buraun",
    "pink": "Pink",

    # ============================================
    # NATURE
    # ============================================
    "tree": "Yat",
    "flower": "Yat manyen",
    "grass": "Lum",
    "animal": "Lebo",
    "dog": "Gwok",
    "cat": "Onyo",
    "cow": "Romo",
    "goat": "Dyell",
    "sheep": "Romnywal",
    "pig": "Pwoc",
    "chicken": "Gweno",
    "bird": "Winyo",
    "lion": "Layeng",
    "elephant": "Lec",
    "snake": "Twon",
    "insect": "Lel",
    "sun": "Ceng",
    "moon": "Dwe",
    "star": "Lak",
    "sky": "Maleng",
    "rain": "Kot",
    "wind": "Yamo",
    "cloud": "Bor",
    "fire": "Mac",
    "smoke": "Wuny mac",
    "hot weather": "Lyer",

    # ============================================
    # MISC COMMON WORDS
    # ============================================
    "name": "Nying",
    "language": "Leb",
    "word": "Lok",
    "book": "Buk",
    "paper": "Karacel",
    "pen": "Biro",
    "phone": "Cim",
    "money": "Pesa",
    "work": "Tic",
    "job": "Tic",
    "price": "Wel",
    "cheap": "Yot",
    "expensive": "Wel tek",
    "free": "Non",
    "gift": "Moto",
    "news": "Lok",
    "story": "Cuny",
    "song": "Wer",
    "music": "Wer",
    "picture": "Cal",
    "photo": "Cal",
    "letter": "Waraga",
    "message": "Lok",
    "problem": "Peko",
    "question": "Penj",
    "answer": "Gamo",
    "idea": "Paro",
    "truth": "Adada",
    "lie": "Lok",
    "love": "Mara",
    "peace": "Kuc",
    "war": "Lweny",
    "water": "Pi",
}

def lookup_acholi(text: str) -> str:
    """Look up English text in the Acholi dictionary"""
    key = text.lower().strip().rstrip('!?.,;:')
    return ACHOLI_DICT.get(key)