"""Ateso (Iteso) - English Dictionary
Comprehensive word list for translation
"""

ATESO_DICT = {
    # ============================================
    # GREETINGS & PLEASANTRIES
    # ============================================
    "good morning": "Ijai eong",
    "good afternoon": "Ijai eong",
    "good evening": "Ijai eong",
    "good night": "Ijoroto",
    "hello": "Yoga",
    "hi": "Yoga",
    "hey": "Yoga",
    "how are you": "Ijaasi",
    "how are you?": "Ijaasi",
    "i am fine": "Eyalama",
    "i'm fine": "Eyalama",
    "i am okay": "Eyalama",
    "nice to meet you": "Aipone ijo",
    "welcome": "Ijai eong",
    "goodbye": "Kwa",
    "bye": "Kwa",
    "see you later": "Kimojong",
    "see you tomorrow": "Kimojong kokoi",
    "take care": "Iworoto",
    "thank you": "Alakara",
    "thanks": "Alakara",
    "thank you very much": "Alakara noi",
    "thanks a lot": "Alakara noi",
    "you're welcome": "Mam",
    "please": "Kosi",
    "sorry": "Akirisi",
    "excuse me": "Akirisi",
    "no problem": "Mam pepe",
    "congratulations": "Aisabai",
    "good luck": "Aipone kaneni",

    # ============================================
    # YES / NO / BASIC
    # ============================================
    "yes": "Eeh",
    "no": "Mam",
    "maybe": "Mam ejai",
    "okay": "Ee",
    "ok": "Ee",
    "alright": "Ee",
    "sure": "Ejai",
    "i don't know": "Mam ngesi",
    "i know": "Ngesi",
    "i agree": "Ngeni",
    "i disagree": "Mam ngeni",
    "correct": "Kaunyara",
    "wrong": "Konyarakin",
    "true": "Ejai",
    "false": "Mam ejai",

    # ============================================
    # QUESTION WORDS
    # ============================================
    "what": "Ngo",
    "what is this": "Ngina ngo",
    "what is that": "Ngina ngo",
    "who": "Nga",
    "who are you": "Ijo nga",
    "where": "Kwo",
    "where are you": "Ijo kwo",
    "where are you going": "Ito kwo",
    "when": "Kaneni",
    "why": "Emamei",
    "how": "Asi",
    "how much": "Aingai",
    "how many": "Aingai",
    "which": "Ngo",
    "what time is it": "Iten aingai",

    # ============================================
    # PERSONAL PRONOUNS
    # ============================================
    "i": "Eong",
    "me": "Eong",
    "you": "Ijo",
    "he": "Nesi",
    "she": "Nesi",
    "it": "Nesi",
    "we": "Iwon",
    "us": "Iwon",
    "they": "Kesi",
    "them": "Kesi",
    "my": "Kaon",
    "your": "Kao",
    "his": "Kesi",
    "her": "Kesi",
    "our": "Kawon",
    "their": "Kakesi",
    "mine": "Kaon",
    "yours": "Kao",

    # ============================================
    # FAMILY
    # ============================================
    "man": "Ekwen",
    "woman": "Aberu",
    "boy": "Ekwen",
    "girl": "Aberu",
    "child": "Idwe",
    "children": "Idwe",
    "baby": "Idwe",
    "father": "Papa",
    "mother": "Mama",
    "son": "Oo",
    "daughter": "Oo",
    "brother": "Itogoi",
    "sister": "Itogoi",
    "family": "Ejakait",
    "friend": "Ekwan",
    "friends": "Ikwan",
    "neighbor": "Emwanai",
    "teacher": "Ekapolon",
    "student": "Ikarak",
    "doctor": "Emuron",
    "nurse": "Emuron",
    "police": "Ipolisi",
    "soldier": "Esikari",
    "driver": "Ekasubakin",
    "farmer": "Ekaimon",
    "trader": "Ekacat",
    "god": "Akuj",
    "lord": "Ekapolon",
    "king": "Emorimor",

    # ============================================
    # NUMBERS
    # ============================================
    "one": "Ediope",
    "two": "Aare",
    "three": "Auni",
    "four": "Aongon",
    "five": "Akany",
    "six": "Akany kaare",
    "seven": "Akany kauni",
    "eight": "Akany kaongon",
    "nine": "Akany kakan",
    "ten": "Itomon",
    "twenty": "Itomon akare",
    "thirty": "Itomon auni",
    "forty": "Itomon aongon",
    "fifty": "Itomon akan",
    "hundred": "Ikaru",
    "thousand": "Ikaru itomon",
    "million": "Ikaru ikaru",

    # ============================================
    # TIME & DAYS
    # ============================================
    "today": "Lolo",
    "yesterday": "Ago",
    "tomorrow": "Kokoi",
    "now": "Nyanya",
    "later": "Kanya",
    "soon": "Kokoi",
    "morning": "Ijai",
    "afternoon": "Ikuta",
    "evening": "Akuan",
    "night": "Awor",
    "day": "Apan",
    "week": "Iwiiki",
    "month": "Elap",
    "year": "Ekait",
    "hour": "Isaa",
    "minute": "Idakika",
    "second": "Isekondi",
    "monday": "Bicel",
    "tuesday": "Bare",
    "wednesday": "Bouni",
    "thursday": "Baongon",
    "friday": "Bakan",
    "saturday": "Bakan",
    "sunday": "Sabiti",
    "time": "Iten",
    "always": "Apei",
    "never": "Mam",
    "sometimes": "Apei",
    "early": "Kokoi",
    "late": "Kawo",

    # ============================================
    # FOOD & DRINK
    # ============================================
    "food": "Akiringan",
    "water": "Keri",
    "milk": "Akile",
    "tea": "Icaai",
    "coffee": "Ikawa",
    "juice": "Ijuisi",
    "soda": "Isoda",
    "beer": "Ajon",
    "bread": "Emukati",
    "rice": "Ocere",
    "beans": "Imuki",
    "meat": "Akinei",
    "chicken": "Akokoyen",
    "beef": "Akinei kaapolon",
    "goat": "Akim",
    "fish": "Akinan",
    "egg": "Ekwang",
    "eggs": "Ikwang",
    "fruit": "Ikanan",
    "banana": "Ibok",
    "mango": "Imuyembe",
    "orange": "Icungwa",
    "pineapple": "Anasi",
    "avocado": "Ovakado",
    "tomato": "Inyanya",
    "onion": "Ekitungulu",
    "potato": "Ibiyaita",
    "cassava": "Emogo",
    "maize": "Emakwi",
    "salt": "Ikom",
    "sugar": "Isukari",
    "oil": "Amoo",
    "honey": "Inyunya",
    "breakfast": "Akiringan ijoi",
    "lunch": "Akiringan apirio",
    "dinner": "Akiringan awor",
    "hungry": "Ailap",
    "i am hungry": "Ailapasi eong",
    "thirsty": "Keri eong",
    "i am thirsty": "Keri eong",
    "delicious": "Ijamu",
    "i want to eat": "Amito eong",

    # ============================================
    # BODY & HEALTH
    # ============================================
    "head": "Akok",
    "eye": "Okon",
    "eyes": "Ikon",
    "ear": "Itiok",
    "nose": "Iluti",
    "mouth": "Iguru",
    "tooth": "Akereka",
    "teeth": "Ikereka",
    "tongue": "Eneke",
    "neck": "Eluti",
    "shoulder": "Ekepolo",
    "arm": "Eke",
    "hand": "Eke",
    "finger": "Akasi",
    "chest": "Iwe",
    "stomach": "Iryo",
    "back": "Aduro",
    "leg": "Ake",
    "foot": "Ake",
    "heart": "Apusi",
    "blood": "Arenya",
    "bone": "Akoso",
    "skin": "Alos",
    "hair": "Aworu",
    "sick": "Aduwan",
    "i am sick": "Aduwan eong",
    "pain": "Ait",
    "hospital": "Odwar",
    "medicine": "Iyo",
    "health": "Aiyalan",
    "life": "Aiyalan",
    "death": "Ato",
    "tired": "Akaun",
    "i am tired": "Akaun eong",
    "sleep": "Iwor",
    "i want to sleep": "Iwor eong",

    # ============================================
    # PLACES & DIRECTIONS
    # ============================================
    "home": "Aban",
    "house": "Aka",
    "school": "Iskul",
    "church": "Ikanisa",
    "market": "Icat",
    "shop": "Aduka",
    "bank": "Ibanka",
    "road": "Ikano",
    "street": "Ikano",
    "city": "Opolon akan",
    "village": "Aban",
    "country": "Aban",
    "world": "Aban",
    "place": "Aitac",
    "here": "Naa",
    "there": "Lolo",
    "everywhere": "Aitac daan",
    "near": "Aiteni",
    "far": "Apak",
    "north": "Aituk",
    "south": "Aitup",
    "east": "Awor",
    "west": "Aituk",
    "up": "Iwor",
    "down": "Apirio",
    "inside": "Ipot",
    "outside": "Kidi",
    "where is the bathroom": "Aitac kapei kwo",
    "where is the market": "Icat kwo",
    "i am lost": "Awor eong",
    "i am going home": "Aban eong",
    "i am going to the market": "Icat eong",

    # ============================================
    # VERBS & ACTIONS
    # ============================================
    "go": "Ito",
    "come": "Piu",
    "eat": "Amito",
    "drink": "Amat",
    "sleep": "Iwor",
    "wake up": "Itil",
    "walk": "Ito",
    "run": "Iriro",
    "sit": "Iwor",
    "stand": "Itil",
    "see": "Irai",
    "look": "Irai",
    "hear": "Ingelu",
    "listen": "Ingelu",
    "speak": "Iwor",
    "talk": "Iwor",
    "say": "Iwor",
    "tell": "Itil",
    "ask": "Igana",
    "answer": "Iwon",
    "give": "Inyolo",
    "take": "Inyolo",
    "bring": "Iwan",
    "send": "Iwor",
    "buy": "Iwon",
    "sell": "Iwo",
    "pay": "Icu",
    "work": "Iwor",
    "play": "Iwor",
    "read": "Ikwon",
    "write": "Iwor",
    "learn": "Iwor",
    "teach": "Iwor",
    "help": "Nyaamu",
    "help me": "Nyaamu eong",
    "wait": "Iwor",
    "stop": "Iwor",
    "start": "Iwor",
    "finish": "Iwor",
    "open": "Iwor",
    "close": "Iwor",
    "enter": "Iwor",
    "exit": "Iwor",
    "know": "Ngesi",
    "understand": "Ngesi",
    "i don't understand": "Mam ngesi",
    "think": "Iwor",
    "want": "Amito",
    "i want": "Amito eong",
    "i don't want": "Mam amito",
    "need": "Amito",
    "love": "Aworu",
    "i love you": "Aworu ijo",
    "like": "Amito",
    "hate": "Iwor",
    "laugh": "Iwor",
    "cry": "Iwor",
    "sing": "Iwor",
    "dance": "Iwor",
    "pray": "Iwor",

    # ============================================
    # ADJECTIVES
    # ============================================
    "good": "Ejai",
    "very good": "Ejai noi",
    "bad": "Mam ejai",
    "very bad": "Mam ejai noi",
    "big": "Apolon",
    "small": "Akori",
    "long": "Awor",
    "short": "Akori",
    "tall": "Awor",
    "new": "Anyun",
    "old": "Kawo",
    "young": "Awor",
    "hot": "Awor",
    "cold": "Awor",
    "warm": "Awor",
    "fast": "Awor",
    "slow": "Awor",
    "easy": "Awor",
    "difficult": "Awor",
    "beautiful": "Ejai",
    "ugly": "Mam ejai",
    "rich": "Ekacat",
    "poor": "Ekapolon",
    "happy": "Ejai",
    "sad": "Mam ejai",
    "angry": "Awor",
    "afraid": "Awor",
    "strong": "Apolon",
    "weak": "Akori",
    "clean": "Ejai",
    "dirty": "Mam ejai",
    "full": "Awor",
    "empty": "Awor",
    "important": "Ejai",
    "possible": "Ejai",
    "impossible": "Mam ejai",

    # ============================================
    # COLORS
    # ============================================
    "color": "Awor",
    "red": "Awor",
    "blue": "Awor",
    "green": "Awor",
    "yellow": "Awor",
    "black": "Awor",
    "white": "Awor",
    "orange": "Awor",
    "brown": "Awor",
    "pink": "Awor",

    # ============================================
    # NATURE & ANIMALS
    # ============================================
    "tree": "Aiti",
    "flower": "Awor",
    "grass": "Awor",
    "animal": "Awor",
    "dog": "Akokoyen",
    "cat": "Awor",
    "cow": "Awor",
    "goat": "Akim",
    "sheep": "Awor",
    "pig": "Awor",
    "chicken": "Akokoyen",
    "bird": "Awor",
    "fish": "Akinan",
    "lion": "Awor",
    "elephant": "Awor",
    "snake": "Awor",
    "insect": "Awor",
    "sun": "Awor",
    "moon": "Elap",
    "star": "Awor",
    "sky": "Awor",
    "rain": "Awor",
    "wind": "Awor",
    "cloud": "Awor",
    "fire": "Awor",
    "smoke": "Awor",

    # ============================================
    # MISC COMMON WORDS
    # ============================================
    "name": "Awor",
    "language": "Awor",
    "word": "Awor",
    "book": "Awor",
    "paper": "Awor",
    "pen": "Awor",
    "phone": "Awor",
    "money": "Isente",
    "work": "Awor",
    "job": "Awor",
    "salary": "Awor",
    "price": "Awor",
    "cheap": "Awor",
    "expensive": "Awor",
    "free": "Awor",
    "gift": "Awor",
    "news": "Awor",
    "story": "Awor",
    "song": "Awor",
    "music": "Awor",
    "picture": "Awor",
    "photo": "Awor",
    "letter": "Awor",
    "message": "Awor",
    "problem": "Awor",
    "question": "Awor",
    "answer": "Awor",
    "idea": "Awor",
    "truth": "Ejai",
    "lie": "Mam ejai",
    "love": "Aworu",
    "peace": "Awor",
    "war": "Awor",
}

def lookup_ateso(text: str) -> str:
    """Look up English text in the Ateso dictionary"""
    key = text.lower().strip().rstrip('!?.,;:')
    return ATESO_DICT.get(key)