"""
Curated everyday phrases and core vocabulary for Ugandan languages + Swahili.
Sits on top of the large JSON corpora and provides the fastest, most accurate
lookup for common speech.
"""

PHRASES = {
    "luganda": {
        "hello": "Oli otya", "hi": "Oli otya",
        "good morning": "Wasuze otya", "good afternoon": "Osiibye otya",
        "good evening": "Osiibye otya", "good night": "Sula bulungi",
        "how are you": "Oli otya", "how are you doing": "Oli otya",
        "i am fine": "Ndi bulungi", "i am okay": "Ndi bulungi",
        "thank you": "Webale", "thank you very much": "Webale nnyo", "thanks": "Webale",
        "goodbye": "Weeraba", "bye": "Weeraba",
        "see you later": "Tunaalabagana", "see you tomorrow": "Tunaalabagana enkya",
        "yes": "Yee", "no": "Nedda", "please": "Mbeela",
        "sorry": "Nsonyiwa", "excuse me": "Nsonyiwa",
        "i love you": "Nkwagala",
        "what is your name": "Oyitibwa ani", "my name is": "Nze",
        "where are you from": "Ova wa", "i am from": "Nva",
        "i am from kampala": "Nva Kampala",
        "how much is this": "Kino kigula ssente mmeka",
        "help me": "Nnyamba", "i need help": "Nneetaaga obuyambi",
        "i do not understand": "Sitegeera", "i understand": "Ntegeera",
        "speak slowly": "Yogera mpola",
        "water": "Amazzi", "food": "Emmere", "market": "Akatale",
        "house": "Ennyumba", "friend": "Mukwano", "my friend": "Mukwano gwange",
        "welcome": "Tukwanirizza", "okay": "Kale",
        "how old are you": "Olina emyaka emeka", "i am hungry": "Njagala emmere",
        "i am thirsty": "Njagala amazzi", "i am tired": "Nkooye",
        "i am happy": "Nneesanyuse", "i am sad": "Nnina ennaku",
        "what happened": "Kiki ekyabadde", "i am sick": "Ndwaadde",
        "call me": "Kuba essimu", "let's go": "Tugende",
        "come here": "Jjangu wano", "go away": "Genda",
        "be careful": "Weetegereze", "don't worry": "Totta kunakuwala",
        "congratulations": "Tukusanyukidde", "happy birthday": "Nnaku za nnaku ennungi",
        "father": "Taata", "mother": "Maama", "brother": "Muganda wange",
        "sister": "Mwannyina wange", "child": "Mwana", "man": "Musajja",
        "woman": "Mukazi", "boy": "Mulenzi", "girl": "Muwala",
        "money": "Ssente", "car": "Emotoka", "bus": "Bbaasi",
        "school": "Ssomero", "hospital": "Ddwaliro", "police": "Poliisi",
        "work": "Omulimu", "book": "Kitabo", "phone": "Essimu",
        "one": "Emu", "two": "Bbiri", "three": "Ssatu", "four": "Nnya",
        "five": "Ttaano", "six": "Mukaaga", "seven": "Musanvu",
        "eight": "Munaana", "nine": "Mwenda", "ten": "Kkumi",
        "today": "Leero", "tomorrow": "Enkya", "yesterday": "Jjo",
        "morning": "Makya", "afternoon": "Ttuntu", "evening": "Akawungeezi",
    },

    "acholi": {
        "hello": "I tye nining", "hi": "I tye nining",
        "good morning": "I tye nining", "good afternoon": "I tye nining",
        "good evening": "I tye nining", "good night": "Otieno maber",
        "how are you": "I tye nining",
        "i am fine": "A tye maber", "i am okay": "A tye maber",
        "thank you": "Apwoyo", "thanks": "Apwoyo", "thank you very much": "Apwoyo matek",
        "goodbye": "Omini", "bye": "Omini",
        "see you later": "Waneno lacen",
        "yes": "Ee", "no": "Pe", "please": "Ki kica",
        "sorry": "Tim kica", "excuse me": "Tim kica",
        "i love you": "A mari",
        "what is your name": "Nyingi nga", "my name is": "Nyinga en",
        "where are you from": "In aa kwene", "i am from": "An aa",
        "i am from gulu": "An aa ki Gulu",
        "how much is this": "Man culu adi",
        "help me": "Konya", "i need help": "A mito kony",
        "i do not understand": "A kwa ngeyo", "i understand": "A ngeyo",
        "speak slowly": "Loki ma piny",
        "water": "Pii", "food": "Kec", "market": "Gwok",
        "house": "Ot", "friend": "Lakwor", "my friend": "Lakworra",
        "welcome": "Ibin wa", "okay": "Ber",
        "how old are you": "Iti nninga mwakka adi",
        "i am hungry": "A mito cam", "i am thirsty": "A mito pii",
        "i am tired": "A ool", "i am happy": "A yom",
        "i am sad": "A kumu", "what happened": "Ngo ma otimme",
        "i am sick": "A two", "call me": "Go cim",
        "let's go": "Wa wot", "come here": "Bin kany",
        "go away": "Wot", "be careful": "Bed ma ber",
        "don't worry": "Pe keki",
        "father": "Wor", "mother": "Meno", "brother": "Omegna",
        "sister": "Nyamega", "child": "Latin", "man": "Laco",
        "woman": "Dako", "boy": "Awobi", "girl": "Nyako",
        "money": "Cent", "car": "Motoka", "bus": "Basi",
        "school": "Cukul", "hospital": "Odit", "police": "Polis",
        "work": "Tic", "book": "Buk", "phone": "Cim",
        "one": "Acel", "two": "Aryo", "three": "Adok",
        "four": "Angwen", "five": "Abic", "six": "Abicel",
        "seven": "Abiryо", "eight": "Aboro", "nine": "Abongwen",
        "ten": "Apar", "today": "Tin", "tomorrow": "Diki",
        "yesterday": "Lacen", "morning": "Odiko", "evening": "Otyeno",
    },

    "runyankole": {
        "hello": "Mwaramutse", "hi": "Mwaramutse",
        "good morning": "Mwaramutse", "good afternoon": "Mwabonaho",
        "good evening": "Mwabonaho", "good night": "Orarire gye",
        "how are you": "Ori ota",
        "i am fine": "Ndi murungi", "i am okay": "Ndi murungi",
        "thank you": "Webare", "thanks": "Webare", "thank you very much": "Webare munonga",
        "goodbye": "Tugyendane", "bye": "Tugyendane",
        "see you later": "Tureebane",
        "yes": "Eego", "no": "Nanga", "please": "Kyangye",
        "sorry": "Ndakwiheka", "excuse me": "Ndakwiheka",
        "i love you": "Ninkukunda",
        "what is your name": "Ibara ryawe nirii", "my name is": "Ibara ryangye ni",
        "where are you from": "Ori rukiraaha", "i am from": "Ninkukira",
        "i am from mbarara": "Ninkukira Mbarara",
        "how much is this": "Eki nikigura ssente zingaahi",
        "help me": "Mpa obuhwezi", "i need help": "Ninkwenda obuhwezi",
        "i do not understand": "Tinkumanya", "i understand": "Ninkumanya",
        "speak slowly": "Gamba gahoro",
        "water": "Amaizi", "food": "Ekyokurya", "market": "Omukyaalo",
        "house": "Enju", "friend": "Munywani", "my friend": "Munywani wangye",
        "welcome": "Mukama waitu", "okay": "Kiri kubi",
        "i am hungry": "Ninkwenda ekyokurya", "i am thirsty": "Ninkwenda amaizi",
        "i am tired": "Naakoye", "i am happy": "Ninkushemererwa",
        "i am sad": "Ninkwebwa", "i am sick": "Ndi murwaire",
        "let's go": "Tugyende", "come here": "Ija aha",
        "be careful": "Weetegereze", "don't worry": "Otarikwata",
        "father": "Taata", "mother": "Maama", "brother": "Mukuru wangye",
        "sister": "Munyaanyazi", "child": "Omwana", "man": "Omushaija",
        "woman": "Omukazi", "money": "Ssente", "car": "Emotoka",
        "school": "Essomero", "hospital": "Edwaariro",
        "work": "Omurimo", "book": "Ekitabo",
        "one": "Kimwe", "two": "Ibiri", "three": "Ishatu",
        "four": "Ina", "five": "Itaanu", "six": "Mukaaga",
        "seven": "Mushanju", "eight": "Munaana", "nine": "Mwenda",
        "ten": "Ikkumi", "today": "Erizooba", "tomorrow": "Nyenkyakare",
        "yesterday": "Nyomwabazyo",
    },

    "swahili": {
        # --- Greetings ---
        "hello": "Habari", "hi": "Habari",
        "good morning": "Habari za asubuhi",
        "good afternoon": "Habari za mchana",
        "good evening": "Habari za jioni",
        "good night": "Usiku mwema",
        "how are you": "Habari yako",
        "i am fine": "Nzuri", "i am okay": "Nzuri",
        "thank you": "Asante", "thanks": "Asante",
        "thank you very much": "Asante sana",
        "goodbye": "Kwaheri", "bye": "Kwaheri",
        "see you later": "Tutaonana baadaye",
        "see you tomorrow": "Tutaonana kesho",
        "yes": "Ndiyo", "no": "Hapana",
        "please": "Tafadhali", "sorry": "Samahani", "excuse me": "Samahani",
        "welcome": "Karibu", "okay": "Sawa", "no problem": "Hakuna shida",
        "i love you": "Nakupenda",
        "what is your name": "Jina lako ni nani",
        "my name is": "Jina langu ni",
        "where are you from": "Unatoka wapi",
        "i am from": "Ninatoka",
        "how much is this": "Hii ni bei gani",
        "help me": "Nisaidie", "i need help": "Nahitaji msaada",
        "i do not understand": "Sielewi", "i understand": "Naelewa",
        "speak slowly": "Sema polepole",
        "how old are you": "Una miaka mingapi",
        "i am hungry": "Nina njaa", "i am thirsty": "Nina kiu",
        "i am tired": "Nimechoka", "i am happy": "Nina furaha",
        "i am sad": "Nina huzuni", "i am sick": "Mimi ni mgonjwa",
        "what happened": "Nini kilitokea",
        "call me": "Nipigie simu", "i will call you": "Nitakupigia simu",
        "let's go": "Twende", "come here": "Njoo hapa", "go away": "Nenda zako",
        "be careful": "Kuwa makini", "i am sorry": "Nasikitika",
        "don't worry": "Usijali", "happy birthday": "Heri ya siku ya kuzaliwa",
        "congratulations": "Hongera",
        # --- Nouns ---
        "water": "Maji", "food": "Chakula", "market": "Soko",
        "house": "Nyumba", "home": "Nyumbani",
        "friend": "Rafiki", "my friend": "Rafiki yangu",
        "family": "Familia", "father": "Baba", "mother": "Mama",
        "brother": "Kaka", "sister": "Dada", "child": "Mtoto",
        "man": "Mtu", "woman": "Mwanamke", "boy": "Mvulana", "girl": "Msichana",
        "money": "Pesa", "car": "Gari", "bus": "Basi", "road": "Barabara",
        "school": "Shule", "hospital": "Hospitali", "police": "Polisi",
        "work": "Kazi", "book": "Kitabu", "phone": "Simu",
        "computer": "Kompyuta", "time": "Wakati", "day": "Siku",
        "night": "Usiku", "morning": "Asubuhi", "afternoon": "Mchana",
        "evening": "Jioni", "week": "Wiki", "month": "Mwezi", "year": "Mwaka",
        "today": "Leo", "tomorrow": "Kesho", "yesterday": "Jana",
        "name": "Jina", "world": "Dunia", "country": "Nchi",
        "city": "Jiji", "village": "Kijiji", "place": "Mahali", "thing": "Kitu",
        "sun": "Jua", "moon": "Mwezi", "star": "Nyota", "rain": "Mvua",
        "wind": "Upepo", "sea": "Bahari", "river": "Mto", "mountain": "Mlima",
        "tree": "Mti", "flower": "Ua", "animal": "Mnyama", "bird": "Ndege",
        "fish": "Samaki", "dog": "Mbwa", "cat": "Paka", "cow": "Ng'ombe",
        "goat": "Mbuzi", "chicken": "Kuku", "egg": "Yai", "milk": "Maziwa",
        "rice": "Wali", "bread": "Mkate", "fruit": "Tunda",
        "vegetable": "Mboga", "meat": "Nyama", "salt": "Chumvi",
        "sugar": "Sukari", "tea": "Chai", "coffee": "Kahawa",
        "clothes": "Nguo", "shoe": "Kiatu", "hat": "Kofia", "bag": "Mfuko",
        "key": "Ufunguo", "door": "Mlango", "window": "Dirisha",
        "table": "Meza", "chair": "Kiti", "bed": "Kitanda", "room": "Chumba",
        "toilet": "Choo", "head": "Kichwa", "eye": "Jicho", "ear": "Sikio",
        "mouth": "Mdomo", "nose": "Pua", "hand": "Mkono", "foot": "Mguu",
        "heart": "Moyo", "blood": "Damu", "bone": "Mfupa", "skin": "Ngozi",
        "hair": "Nywele", "tooth": "Jino", "tongue": "Ulimi",
        # --- Numbers ---
        "one": "Moja", "two": "Mbili", "three": "Tatu", "four": "Nne",
        "five": "Tano", "six": "Sita", "seven": "Saba", "eight": "Nane",
        "nine": "Tisa", "ten": "Kumi", "eleven": "Kumi na moja",
        "twelve": "Kumi na mbili", "twenty": "Ishirini",
        "thirty": "Thelathini", "forty": "Arobaini", "fifty": "Hamsini",
        "hundred": "Mia", "thousand": "Elfu",
        # --- Verbs ---
        "to eat": "Kula", "to drink": "Kunywa", "to sleep": "Kulala",
        "to work": "Kufanya kazi", "to speak": "Kusema",
        "to listen": "Kusikiliza", "to see": "Kuona", "to know": "Kujua",
        "to want": "Kutaka", "to need": "Kuhitaji", "to like": "Kupenda",
        "to go": "Kwenda", "to come": "Kuja",
        # --- Adjectives ---
        "good": "Nzuri", "bad": "Mbaya", "big": "Kubwa", "small": "Ndogo",
        "new": "Mpya", "old": "Zee", "hot": "Moto", "cold": "Baridi",
        "fast": "Haraka", "slow": "Polepole",
        "beautiful": "Mzuri", "strong": "Nguvu", "weak": "Dhaifu",
        "easy": "Rahisi", "hard": "Ngumu",
        # --- Questions ---
        "what": "Nini", "who": "Nani", "where": "Wapi",
        "when": "Lini", "why": "Kwa nini", "how": "Vipi",
        "how many": "Ngapi", "how much": "Kiasi gani",
        # --- Days ---
        "monday": "Jumatatu", "tuesday": "Jumanne", "wednesday": "Jumatano",
        "thursday": "Alhamisi", "friday": "Ijumaa",
        "saturday": "Jumamosi", "sunday": "Jumapili",
        # --- Phrases ---
        "i am going to the market": "Ninaenda sokoni",
        "where is the market": "Soko liko wapi",
        "i want to buy": "Nataka kununua",
        "how much does this cost": "Hii inagharimu kiasi gani",
        "too expensive": "Ghali sana",
        "i am looking for": "Natafuta",
        "can you help me": "Unaweza kunisaidia",
        "i don't know": "Sijui", "i don't want": "Sitaki",
        "i want to go home": "Nataka kwenda nyumbani",
        "i am lost": "Nimepotea",
        "call the police": "Piga polisi",
        "i need a doctor": "Nahitaji daktari",
        "where is the hospital": "Hospitali iko wapi",
        "i have a headache": "Nina maumivu ya kichwa",
        "i have a fever": "Nina homa",
        "i have a stomachache": "Nina maumivu ya tumbo",
        "where is the bathroom": "Choo kiko wapi",
        "i would like a room": "Ningependa chumba",
        "how much per night": "Kiasi gani kwa usiku",
        "is breakfast included": "Kiamsha kinywa kimejumuishwa",
        "can i see the menu": "Naweza kuona menyu",
        "i would like to order": "Ningependa kuagiza",
        "the bill please": "Bili tafadhali",
        "delicious": "Tamu", "i am full": "Nimeshiba",
        "where can i buy a ticket": "Naweza kununua tikiti wapi",
        "what time does it leave": "Inaondoka saa ngapi",
        "i missed my train": "Nimekosa treni yangu",
        "where is the bus stop": "Kituo cha basi kiko wapi",
        "the weather is nice today": "Hali ya hewa ni nzuri leo",
        "it is raining": "Inanyesha", "it is hot": "Kuna joto", "it is cold": "Kuna baridi",
    },

    "ateso": {
        "hello": "Yoga", "hi": "Yoga",
        "good morning": "Itooma noi", "how are you": "Itooma noi",
        "i am fine": "Atooma",
        "thank you": "Alakara", "thanks": "Alakara",
        "thank you very much": "Alakara noi",
        "goodbye": "Kokis", "yes": "Eeh", "no": "Mam",
        "please": "Kworot", "sorry": "Nyikan",
        "i love you": "Anyaramai",
        "what is your name": "Ejakait kon", "my name is": "Ejakait kang",
        "water": "Ekwai", "food": "Apon", "house": "Adukot",
        "friend": "Ekoni", "man": "Ekile", "woman": "Abanan",
        "child": "Idwe", "money": "Esente",
        "one": "Ediope", "two": "Aarei", "three": "Auni",
        "four": "Aongon", "five": "Akony", "ten": "Itomon",
        "today": "Lolo", "tomorrow": "Moi", "yesterday": "Jaan",
    },

    "rukiga": {
        "hello": "Mwaramutse", "good morning": "Mwaramutse",
        "good afternoon": "Mwabonaho", "how are you": "Ori ota",
        "i am fine": "Ndi murungi",
        "thank you": "Webare", "thanks": "Webare",
        "thank you very much": "Webare munonga",
        "goodbye": "Tugyendane", "yes": "Eego", "no": "Nanga",
        "please": "Kyangye", "sorry": "Ndakwiheka",
        "i love you": "Ninkukunda",
        "what is your name": "Ibara ryawe nirii",
        "my name is": "Ibara ryangye ni",
        "water": "Amaizi", "food": "Ekyokurya", "house": "Enju",
        "friend": "Munywani", "man": "Omushaija", "woman": "Omukazi",
        "child": "Omwana", "money": "Ssente",
        "one": "Kimwe", "two": "Ibiri", "three": "Ishatu",
        "four": "Ina", "five": "Itaanu", "ten": "Ikkumi",
        "today": "Erizooba", "tomorrow": "Nyenkyakare",
    },

    "alur": {
        "hello": "Mirembe", "good morning": "Iya maber",
        "how are you": "Itye nining", "i am fine": "Atye maber",
        "thank you": "Apwoyo", "thanks": "Apwoyo",
        "goodbye": "Oriti", "yes": "Ee", "no": "Pe",
        "please": "Yik", "i love you": "Amari",
        "water": "Pii", "food": "Chiem", "house": "Ot",
        "friend": "Lakwor", "man": "Laco", "woman": "Dako",
        "child": "Latin", "money": "Cent",
        "one": "Acel", "two": "Aryo", "three": "Adok",
        "four": "Angwen", "five": "Abic", "ten": "Apar",
    },
}

# ============================================================
# Reverse lookup (native → English) — auto-built from PHRASES
# ============================================================

REVERSE = {}
for _lang, _pairs in PHRASES.items():
    REVERSE[_lang] = {}
    for _en, _native in _pairs.items():
        _key = _native.lower().strip()
        if _key not in REVERSE[_lang]:
            REVERSE[_lang][_key] = _en