"""
Curated everyday phrases for Ugandan languages.
Supplements the large Bible-based corpora with conversational phrases
that users actually speak.

Structure:
  PHRASES[language][english_phrase] = native_translation
  REVERSE[language][native_phrase] = english_phrase
"""

# ============================================================
# English → Native
# ============================================================

PHRASES = {
    "luganda": {
        "hello": "Oli otya",
        "hi": "Oli otya",
        "good morning": "Wasuze otya",
        "good afternoon": "Osiibye otya",
        "good evening": "Osiibye otya",
        "good night": "Sula bulungi",
        "how are you": "Oli otya",
        "how are you doing": "Oli otya",
        "i am fine": "Ndi bulungi",
        "i am okay": "Ndi bulungi",
        "thank you": "Webale",
        "thank you very much": "Webale nnyo",
        "thanks": "Webale",
        "goodbye": "Weeraba",
        "bye": "Weeraba",
        "see you later": "Tunaalabagana",
        "see you tomorrow": "Tunaalabagana enkya",
        "yes": "Yee",
        "no": "Nedda",
        "please": "Mbeela",
        "sorry": "Nsonyiwa",
        "excuse me": "Nsonyiwa",
        "i love you": "Nkwagala",
        "what is your name": "Oyitibwa ani",
        "my name is": "Nze",
        "where are you from": "Ova wa",
        "i am from": "Nva",
        "i am from kampala": "Nva Kampala",
        "how much is this": "Kino kigula ssente mmeka",
        "help me": "Nnyamba",
        "i need help": "Nneetaaga obuyambi",
        "i do not understand": "Sitegeera",
        "i understand": "Ntegeera",
        "speak slowly": "Yogera mpola",
        "water": "Amazzi",
        "food": "Emmere",
        "market": "Akatale",
        "house": "Ennyumba",
        "friend": "Mukwano",
        "my friend": "Mukwano gwange",
    },

    "acholi": {
        "hello": "I tye nining",
        "hi": "I tye nining",
        "good morning": "I tye nining",
        "good afternoon": "I tye nining",
        "good evening": "I tye nining",
        "good night": "Otieno maber",
        "how are you": "I tye nining",
        "i am fine": "A tye maber",
        "i am okay": "A tye maber",
        "thank you": "Apwoyo",
        "thanks": "Apwoyo",
        "thank you very much": "Apwoyo matek",
        "goodbye": "Omini",
        "bye": "Omini",
        "see you later": "Waneno lacen",
        "yes": "Ee",
        "no": "Pe",
        "please": "Ki kica",
        "sorry": "Tim kica",
        "excuse me": "Tim kica",
        "i love you": "A mari",
        "what is your name": "Nyingi nga",
        "my name is": "Nyinga en",
        "where are you from": "In aa kwene",
        "i am from": "An aa",
        "i am from gulu": "An aa ki Gulu",
        "how much is this": "Man culu adi",
        "help me": "Konya",
        "i need help": "A mito kony",
        "i do not understand": "A kwa ngeyo",
        "i understand": "A ngeyo",
        "water": "Pii",
        "food": "Kec",
        "market": "Gwok",
        "house": "Ot",
        "friend": "Lakwor",
        "my friend": "Lakworra",
    },

    "runyankole": {
        "hello": "Mwaramutse",
        "hi": "Mwaramutse",
        "good morning": "Mwaramutse",
        "good afternoon": "Mwabonaho",
        "good evening": "Mwabonaho",
        "good night": "Orarire gye",
        "how are you": "Ori ota",
        "i am fine": "Ndi murungi",
        "i am okay": "Ndi murungi",
        "thank you": "Webare",
        "thanks": "Webare",
        "thank you very much": "Webare munonga",
        "goodbye": "Tugyendane",
        "bye": "Tugyendane",
        "see you later": "Tureebane",
        "yes": "Eego",
        "no": "Nanga",
        "please": "Kyangye",
        "sorry": "Ndakwiheka",
        "excuse me": "Ndakwiheka",
        "i love you": "Ninkukunda",
        "what is your name": "Ibara ryawe nirii",
        "my name is": "Ibara ryangye ni",
        "where are you from": "Ori rukiraaha",
        "i am from": "Ninkukira",
        "i am from mbarara": "Ninkukira Mbarara",
        "how much is this": "Eki nikigura ssente zingaahi",
        "help me": "Mpa obuhwezi",
        "i need help": "Ninkwenda obuhwezi",
        "i do not understand": "Tinkumanya",
        "i understand": "Ninkumanya",
        "water": "Amaizi",
        "food": "Ekyokurya",
        "market": "Omukyaalo",
        "house": "Enju",
        "friend": "Munywani",
        "my friend": "Munywani wangye",
    },

    "swahili": {
        "hello": "Habari",
        "hi": "Habari",
        "good morning": "Habari za asubuhi",
        "good afternoon": "Habari za mchana",
        "good evening": "Habari za jioni",
        "good night": "Usiku mwema",
        "how are you": "Habari yako",
        "i am fine": "Nzuri",
        "i am okay": "Nzuri",
        "thank you": "Asante",
        "thanks": "Asante",
        "thank you very much": "Asante sana",
        "goodbye": "Kwaheri",
        "bye": "Kwaheri",
        "see you later": "Tutaonana baadaye",
        "yes": "Ndiyo",
        "no": "Hapana",
        "please": "Tafadhali",
        "sorry": "Samahani",
        "excuse me": "Samahani",
        "i love you": "Nakupenda",
        "what is your name": "Jina lako ni nani",
        "my name is": "Jina langu ni",
        "where are you from": "Unatoka wapi",
        "i am from": "Ninatoka",
        "how much is this": "Hii ni bei gani",
        "help me": "Nisaidie",
        "i need help": "Nahitaji msaada",
        "i do not understand": "Sielewi",
        "i understand": "Naelewa",
        "water": "Maji",
        "food": "Chakula",
        "market": "Soko",
        "house": "Nyumba",
        "friend": "Rafiki",
        "my friend": "Rafiki yangu",
    },

    "ateso": {
        "hello": "Yoga",
        "hi": "Yoga",
        "good morning": "Itooma noi",
        "how are you": "Itooma noi",
        "i am fine": "Atooma",
        "thank you": "Alakara",
        "thanks": "Alakara",
        "thank you very much": "Alakara noi",
        "goodbye": "Kokis",
        "yes": "Eeh",
        "no": "Mam",
        "please": "Kworot",
        "sorry": "Nyikan",
        "i love you": "Anyaramai",
        "what is your name": "Ejakait kon",
        "my name is": "Ejakait kang",
        "water": "Ekwai",
        "food": "Apon",
        "house": "Adukot",
    },

    "rukiga": {
        "hello": "Mwaramutse",
        "good morning": "Mwaramutse",
        "good afternoon": "Mwabonaho",
        "how are you": "Ori ota",
        "i am fine": "Ndi murungi",
        "thank you": "Webare",
        "thanks": "Webare",
        "thank you very much": "Webare munonga",
        "goodbye": "Tugyendane",
        "yes": "Eego",
        "no": "Nanga",
        "please": "Kyangye",
        "sorry": "Ndakwiheka",
        "i love you": "Ninkukunda",
        "what is your name": "Ibara ryawe nirii",
        "my name is": "Ibara ryangye ni",
        "water": "Amaizi",
        "food": "Ekyokurya",
        "house": "Enju",
    },

    "alur": {
        "hello": "Mirembe",
        "good morning": "Iya maber",
        "how are you": "Itye nining",
        "i am fine": "Atye maber",
        "thank you": "Apwoyo",
        "thanks": "Apwoyo",
        "goodbye": "Oriti",
        "yes": "Ee",
        "no": "Pe",
        "please": "Yik",
        "i love you": "Amari",
        "water": "Pii",
        "food": "Chiem",
        "house": "Ot",
    },
}

# ============================================================
# Reverse lookup (native → English) — auto-built from PHRASES
# ============================================================

REVERSE = {}
for _lang, _pairs in PHRASES.items():
    REVERSE[_lang] = {}
    for _en, _native in _pairs.items():
        _key = _native.lower().strip()
        if _key not in REVERSE[_lang]:
            REVERSE[_lang][_key] = _en