"""Luganda - English Dictionary
Comprehensive word list for translation
"""

LUGANDA_DICT = {
    # ============================================
    # GREETINGS & PLEASANTRIES
    # ============================================
    "good morning": "Wasuze otya",
    "good afternoon": "Osiibye otya",
    "good evening": "Osiibye otya",
    "good night": "Sula bulungi",
    "hello": "Oli otya",
    "hi": "Oli otya",
    "hey": "Oli otya",
    "how are you": "Oli otya",
    "how are you?": "Oli otya",
    "how are you doing": "Oli otya",
    "how is it going": "Ki kati",
    "what's up": "Ki kati",
    "i am fine": "Gyendi",
    "i'm fine": "Gyendi",
    "i am okay": "Gyendi",
    "i am good": "Gyendi",
    "not bad": "Kyetagisa",
    "nice to meet you": "Nkusiimye okukulaba",
    "long time no see": "Ebbanga ddene",
    "welcome": "Tukwanirizza",
    "welcome back": "Tukwanirizza nate",
    "goodbye": "Weraba",
    "bye": "Weraba",
    "see you later": "Tunaalabagana",
    "see you tomorrow": "Tunaalabagana enkya",
    "see you soon": "Tunaalabagana mangu",
    "take care": "Weefube",
    "have a nice day": "Sanyuka olunaku",
    "have a good trip": "Genda bulungi",
    "safe journey": "Genda bulungi",

    # ============================================
    # POLITE EXPRESSIONS
    # ============================================
    "thank you": "Webale",
    "thanks": "Webale",
    "thank you very much": "Webale nyo",
    "thanks a lot": "Webale nyo",
    "many thanks": "Webale nyo",
    "you're welcome": "Kikwetaagisa",
    "please": "Mwattu",
    "sorry": "Nsonyiwa",
    "i am sorry": "Nsonyiwa",
    "excuse me": "Nsonyiwa",
    "pardon me": "Nsonyiwa",
    "no problem": "Ttezibu",
    "it's okay": "Kiri bulungi",
    "don't worry": "Teweeraliikirira",
    "congratulations": "Tukwebaza",
    "well done": "Kikoleddwa bulungi",
    "good luck": "Omukisa omulungi",
    "happy birthday": "Nkwagaliza olunaku olulungi",
    "happy new year": "Nkwagaliza omwaka omupya",
    "merry christmas": "Nkwagaliza Sekukkulu",
    "best wishes": "Ebisuubizo ebirungi",

    # ============================================
    # YES / NO / BASIC
    # ============================================
    "yes": "Yee",
    "no": "Nedda",
    "maybe": "Oboolyawo",
    "okay": "Kale",
    "ok": "Kale",
    "alright": "Kale",
    "sure": "Mazima",
    "of course": "Kya mazima",
    "i don't know": "Simanyi",
    "i know": "Mmanyi",
    "i think so": "Ndeka bwe kityo",
    "i don't think so": "Sindowooza bwe kityo",
    "i agree": "Nkikkiriza",
    "i disagree": "Sikkiriza",
    "correct": "Kituufu",
    "wrong": "Kikyamu",
    "right": "Kutuufu",
    "left": "Kkono",
    "true": "Mazima",
    "false": "Kikyamu",

    # ============================================
    # QUESTION WORDS
    # ============================================
    "what": "Ki",
    "what is this": "Kino ki",
    "what is that": "Kiri ki",
    "who": "Ani",
    "who are you": "Ggwe ani",
    "where": "Wa",
    "where are you": "Oli wa",
    "where are you going": "Ogenda wa",
    "when": "Ddi",
    "why": "Lwaki",
    "how": "Otya",
    "how much": "Mmeka",
    "how much is this": "Kino kigula ssente mmeka",
    "how many": "Bbweka",
    "which": "Ki",
    "whose": "Wa ani",
    "what time is it": "Ssaawa mmeka",

    # ============================================
    # PERSONAL PRONOUNS
    # ============================================
    "i": "Nze",
    "me": "Nze",
    "you": "Ggwe",
    "he": "Ye",
    "she": "Ye",
    "it": "Kyo",
    "we": "Ffe",
    "us": "Ffe",
    "they": "Bo",
    "them": "Bo",
    "my": "Wange",
    "your": "Woo",
    "his": "We",
    "her": "We",
    "our": "Waffe",
    "their": "Waabwe",
    "mine": "Kyange",
    "yours": "Kyo",

    # ============================================
    # FAMILY
    # ============================================
    "man": "Musajja",
    "woman": "Mukazi",
    "boy": "Mulenzi",
    "girl": "Muwala",
    "child": "Mwana",
    "children": "Baana",
    "baby": "Kiboyi",
    "father": "Taata",
    "mother": "Maama",
    "son": "Mutabani",
    "daughter": "Muwala",
    "brother": "Muganda",
    "sister": "Muganda",
    "family": "Amaka",
    "friend": "Mukwano",
    "friends": "Mikwano",
    "neighbor": "Muliraanwa",
    "teacher": "Omusomesa",
    "student": "Omuyizi",
    "doctor": "Omusawo",
    "nurse": "Omujjanjabi",
    "police": "Poliisi",
    "soldier": "Omuserikale",
    "driver": "Omuvuzi",
    "farmer": "Omulimi",
    "trader": "Omusuubuzi",
    "customer": "Omuguzi",
    "guest": "Omugenyi",
    "stranger": "Omugenyi",
    "god": "Katonda",
    "lord": "Mukama",
    "king": "Kabaka",
    "chief": "Ow'ekika",

    # ============================================
    # NUMBERS
    # ============================================
    "one": "Emu",
    "two": "Bbiri",
    "three": "Ssatu",
    "four": "Nnya",
    "five": "Ttaano",
    "six": "Mukaaga",
    "seven": "Musanvu",
    "eight": "Munaana",
    "nine": "Mwenda",
    "ten": "Kkumi",
    "eleven": "Kkumi na emu",
    "twelve": "Kkumi na bbiri",
    "twenty": "Amakumi abiri",
    "thirty": "Amakumi asatu",
    "forty": "Amakumi ana",
    "fifty": "Amakumi ataano",
    "sixty": "Amakumi mukaaga",
    "seventy": "Amakumi musanvu",
    "eighty": "Amakumi munaana",
    "ninety": "Amakumi mwenda",
    "hundred": "Kikumi",
    "thousand": "Lukumi",
    "million": "Akakadde",
    "first": "Eyakubiri",
    "second": "Eyakubiri",
    "third": "Eyasatu",
    "last": "Eyasembayo",

    # ============================================
    # TIME & DATES
    # ============================================
    "today": "Leero",
    "yesterday": "Eggulo",
    "tomorrow": "Enkya",
    "now": "Kaakano",
    "later": "Oluvannyuma",
    "soon": "Mangu",
    "morning": "Enkya",
    "afternoon": "Ettuntu",
    "evening": "Akawungeezi",
    "night": "Ekiro",
    "day": "Olunaku",
    "week": "Wiiki",
    "month": "Mwezi",
    "year": "Mwaka",
    "hour": "Ssaawa",
    "minute": "Eddakiika",
    "second": "Sekonda",
    "monday": "Balaza",
    "tuesday": "Lwakubiri",
    "wednesday": "Lwakusatu",
    "thursday": "Lwakuna",
    "friday": "Lwakutaano",
    "saturday": "Lwamukaaga",
    "sunday": "Sabbiiti",
    "time": "Ekiseera",
    "always": "Buli kiseera",
    "never": "Tewali",
    "sometimes": "Ebiseera ebimu",
    "often": "Emirundi mingi",
    "early": "Mangu",
    "late": "Ekyayita",

    # ============================================
    # FOOD & DRINK
    # ============================================
    "food": "Emmere",
    "water": "Amazzi",
    "milk": "Amata",
    "tea": "Caayi",
    "coffee": "Kawa",
    "juice": "Omuwemba",
    "soda": "Soda",
    "beer": "Kyaayi",
    "wine": "Wayini",
    "bread": "Emugaati",
    "rice": "Omuceere",
    "beans": "Ebijanjaalo",
    "meat": "Ennyama",
    "chicken": "Enkoko",
    "beef": "Ennyama y'ente",
    "goat": "Embuzi",
    "fish": "Ekyennyanja",
    "egg": "Egga",
    "eggs": "Amagi",
    "fruit": "Ekibala",
    "banana": "Ekitooke",
    "matooke": "Ebitooke",
    "mango": "Muyaaye",
    "orange": "Omucungwa",
    "pineapple": "Anaasi",
    "avocado": "Ovakado",
    "tomato": "Enyanya",
    "onion": "Ekitungulu",
    "potato": "Kikoola",
    "cassava": "Muwogo",
    "maize": "Kasooli",
    "corn": "Kasooli",
    "groundnut": "Ebinyeebwa",
    "peanut": "Ebinyeebwa",
    "salt": "Omunnyo",
    "sugar": "Sukali",
    "pepper": "Omuwendo",
    "oil": "Amafuta",
    "honey": "Omubisi",
    "breakfast": "Ekyekiro",
    "lunch": "Ekyemisana",
    "dinner": "Ekyeggulo",
    "hungry": "Enjala",
    "i am hungry": "Ndaba enjala",
    "thirsty": "Enyonta",
    "i am thirsty": "Ndaba ennyonta",
    "delicious": "Kiwooma",
    "tasty": "Kiwooma",

    # ============================================
    # BODY & HEALTH
    # ============================================
    "head": "Omutwe",
    "eye": "Eriiso",
    "eyes": "Amaaso",
    "ear": "Ekkutu",
    "nose": "Ennyindo",
    "mouth": "Akamwa",
    "tooth": "Erinnyo",
    "teeth": "Amannyo",
    "tongue": "Olulimi",
    "neck": "Ensingo",
    "shoulder": "Ekibega",
    "arm": "Omukono",
    "hand": "Omukono",
    "finger": "Olugalo",
    "chest": "Ekifuba",
    "stomach": "Olubuto",
    "back": "Omugongo",
    "leg": "Okugulu",
    "foot": "Ekigere",
    "heart": "Omutima",
    "blood": "Omusaayi",
    "bone": "Eggumba",
    "skin": "Olususu",
    "hair": "Enviiri",
    "sick": "Olwadde",
    "i am sick": "Ndwaadde",
    "pain": "Obulumi",
    "i have a headache": "Ndina omutwe",
    "hospital": "Eddwaliro",
    "medicine": "Eddagala",
    "health": "Obulamu",
    "life": "Obulamu",
    "death": "Okufa",
    "tired": "Nkooye",
    "i am tired": "Nkooye",
    "sleep": "Otulo",
    "i want to sleep": "Njagala otulo",

    # ============================================
    # PLACES & DIRECTIONS
    # ============================================
    "home": "Eka",
    "house": "Ennyumba",
    "school": "Essomero",
    "church": "Ekkanisa",
    "mosque": "Omuzikiti",
    "market": "Akatale",
    "shop": "Aduuka",
    "store": "Aduuka",
    "bank": "Banka",
    "police station": "Poliisi",
    "road": "Oluguudo",
    "street": "Oluguudo",
    "city": "Ekibuga",
    "village": "Ekyalo",
    "country": "Ensi",
    "world": "Ensi",
    "place": "Ekifo",
    "here": "Wano",
    "there": "Wali",
    "everywhere": "Buli wamu",
    "near": "Kumpi",
    "far": "Wala",
    "north": "Obukiika obwa kkono",
    "south": "Obukiika obwa ddyo",
    "east": "Buvanjuba",
    "west": "Bugwanjuba",
    "up": "Waggulu",
    "down": "Wansi",
    "inside": "Munda",
    "outside": "Ebweru",
    "where is the bathroom": "Enyumba y'omuyigo eri ludda wa",
    "where is the market": "Akatale kali ludda wa",
    "i am lost": "Nzibye",
    "i am going home": "Ndi kugenda eka",
    "i am going to the market": "Ndi kugenda mu katale",

    # ============================================
    # VERBS & ACTIONS
    # ============================================
    "go": "Genda",
    "come": "Jjangu",
    "eat": "Lya",
    "drink": "Nywa",
    "sleep": "Sula",
    "wake up": "Zuuukuka",
    "walk": "Tambula",
    "run": "Dduka",
    "sit": "Tuula",
    "stand": "Yimirira",
    "see": "Laba",
    "look": "Laba",
    "hear": "Wulira",
    "listen": "Wuliriza",
    "speak": "Yogera",
    "talk": "Yogera",
    "say": "Gamba",
    "tell": "Tegeeza",
    "ask": "Buuza",
    "answer": "Ddamu",
    "give": "Wa",
    "take": "Twala",
    "bring": "Leeta",
    "send": "Tuma",
    "buy": "Gula",
    "sell": "Tunda",
    "pay": "Sasula",
    "work": "Kola",
    "play": "Zannya",
    "read": "Soma",
    "write": "Wandiika",
    "learn": "Yiga",
    "teach": "Yigiriza",
    "help": "Yamba",
    "help me": "Nnyamba",
    "wait": "Linda",
    "stop": "Yimirira",
    "start": "Tandika",
    "finish": "Maliriza",
    "open": "Ggulawo",
    "close": "Ggalawo",
    "enter": "Yingira",
    "exit": "Fuluma",
    "know": "Manya",
    "understand": "Tegeera",
    "i don't understand": "Sitegeera",
    "think": "Lowooza",
    "want": "Agala",
    "i want": "Njagala",
    "i don't want": "Ssaagala",
    "need": "Beetaaga",
    "i need help": "Nneetaaga obuyambi",
    "love": "Kwagaala",
    "i love you": "Nkwagala",
    "like": "Siima",
    "i like it": "Nkisiima",
    "hate": "Kyawa",
    "laugh": "Seka",
    "cry": "Kaaba",
    "sing": "Yimba",
    "dance": "Zina",
    "pray": "Saba",

    # ============================================
    # ADJECTIVES
    # ============================================
    "good": "Kirungi",
    "very good": "Kirungi nyo",
    "bad": "Kibi",
    "very bad": "Kibi nyo",
    "big": "Kinene",
    "small": "Kitono",
    "long": "Kiwanvu",
    "short": "Kitono",
    "tall": "Muwanvu",
    "new": "Kipya",
    "old": "Kikadde",
    "young": "Muto",
    "hot": "Kyokya",
    "cold": "Kinyogoga",
    "warm": "Kyokya",
    "fast": "Mangu",
    "slow": "Lubye",
    "easy": "Kyangu",
    "difficult": "Kizibu",
    "hard": "Kizibu",
    "beautiful": "Mulungi",
    "pretty": "Mulungi",
    "handsome": "Mulungi",
    "ugly": "Mubi",
    "rich": "Mugagga",
    "poor": "Muyavu",
    "happy": "Musanyufu",
    "sad": "Munakuwavu",
    "angry": "Musunguwavu",
    "afraid": "Mutya",
    "strong": "Muzira",
    "weak": "Munafu",
    "clean": "Mulongoofu",
    "dirty": "Mukyafu",
    "full": "Mujjudde",
    "empty": "Mwalirira",
    "same": "Kye kimu",
    "different": "Kya njawulo",
    "important": "Kikulu",
    "possible": "Kisoboka",
    "impossible": "Tekisoboka",

    # ============================================
    # COLORS
    # ============================================
    "color": "Langi",
    "red": "Myufu",
    "blue": "Bulu",
    "green": "Kiragala",
    "yellow": "Kyenvu",
    "black": "Ddira",
    "white": "Jeru",
    "orange": "Mucungwa",
    "purple": "Bulu bw'amabega",
    "brown": "Kikulukusi",
    "pink": "Kiragala ky'amakula",

    # ============================================
    # NATURE & ANIMALS
    # ============================================
    "tree": "Omuti",
    "flower": "Ekyuma",
    "grass": "Essubi",
    "animal": "Ensolo",
    "dog": "Embwa",
    "cat": "Kapa",
    "cow": "Ente",
    "goat": "Embuzi",
    "sheep": "Endiga",
    "pig": "Embizzi",
    "chicken": "Enkoko",
    "bird": "Ekinyonyi",
    "fish": "Ekyennyanja",
    "lion": "Empologoma",
    "elephant": "Enjovu",
    "snake": "Omusota",
    "insect": "Ekiwuka",
    "sun": "Enjuba",
    "moon": "Omwezi",
    "star": "Ennyonyi",
    "sky": "Eggulu",
    "rain": "Enkuba",
    "wind": "Embuyaga",
    "cloud": "Ekire",
    "fire": "Omuliro",
    "smoke": "Omukka",
    "weather": "Obudde",

    # ============================================
    # MISC COMMON WORDS
    # ============================================
    "name": "Erinnya",
    "language": "Olulimi",
    "word": "Ekigambo",
    "book": "Ekitabo",
    "paper": "Olupapula",
    "pen": "Ekirimba",
    "phone": "Essimu",
    "computer": "Kompyuta",
    "car": "Emotoka",
    "bicycle": "Egaali",
    "motorcycle": "Pikipiki",
    "bus": "Basi",
    "train": "Eggaali y'omukka",
    "airplane": "Ennyonyi",
    "boat": "Eryato",
    "money": "Ssente",
    "work": "Omulimu",
    "job": "Omulimu",
    "salary": "Empeera",
    "price": "Omuwendo",
    "cheap": "Kyangu",
    "expensive": "Kya bbeyi",
    "free": "Kya bwereere",
    "gift": "Ekirabo",
    "news": "Amawulire",
    "story": "Olugero",
    "song": "Oluyimba",
    "music": "Omuziki",
    "picture": "Ekifaananyi",
    "photo": "Ekifaananyi",
    "letter": "Ebbaluwa",
    "email": "Ebbaluwa ya kompyuta",
    "message": "Obubaka",
    "problem": "Ekizibu",
    "question": "Ekibuuzo",
    "answer": "Eky'okuddamu",
    "idea": "Ekirowoozo",
    "truth": "Amazima",
    "lie": "Obulimba",
    "love": "Okwagala",
    "peace": "Emirembe",
    "war": "Entalo",
}

def lookup_luganda(text: str) -> str:
    """Look up English text in the Luganda dictionary"""
    key = text.lower().strip().rstrip('!?.,;:')
    return LUGANDA_DICT.get(key)