"""Rukiga / Runyankole - English Dictionary
Comprehensive word list for translation
Note: Rukiga and Runyankole are closely related dialects and share most vocabulary.
"""

RUKIGA_DICT = {
    # ============================================
    # GREETINGS & PLEASANTRIES
    # ============================================
    "good morning": "Oraire ota",
    "good afternoon": "Osiibire ota",
    "good evening": "Osiibire ota",
    "good night": "Orare kurungi",
    "hello": "Oraire ota",
    "hi": "Oraire ota",
    "hey": "Oraire ota",
    "how are you": "Oraire ota",
    "how are you?": "Oraire ota",
    "how are you doing": "Oraire ota",
    "how is it going": "Nkooki",
    "what's up": "Nkooki",
    "i am fine": "Ndi kurungi",
    "i'm fine": "Ndi kurungi",
    "i am okay": "Ndi kurungi",
    "i am good": "Ndi kurungi",
    "not bad": "Tikibi",
    "nice to meet you": "Nkusiimire okukureeba",
    "welcome": "Mwaramutsire",
    "goodbye": "Osiibe kurungi",
    "bye": "Osiibe kurungi",
    "see you later": "Tureebane",
    "see you tomorrow": "Tureebane nyenkyakare",
    "see you soon": "Tureebane vuba",
    "take care": "Weijune",
    "have a nice day": "Osiibe kurungi",

    # ============================================
    # POLITE EXPRESSIONS
    # ============================================
    "thank you": "Webare",
    "thanks": "Webare",
    "thank you very much": "Webare munonga",
    "thanks a lot": "Webare munonga",
    "many thanks": "Webare munonga",
    "you're welcome": "Neeza",
    "please": "Mbwenu",
    "sorry": "Nsonyiwa",
    "i am sorry": "Nsonyiwa",
    "excuse me": "Nsonyiwa",
    "pardon me": "Nsonyiwa",
    "no problem": "Tihariho kizibu",
    "it's okay": "Ni kirungi",
    "don't worry": "Otatina",
    "congratulations": "Tukuhaisa omukisa",
    "well done": "Wakozire kurungi",
    "good luck": "Omukisa murungi",
    "happy birthday": "Kuhimbise oruzaaro",
    "happy new year": "Omwaka omupya murungi",
    "merry christmas": "Noeli nungi",

    # ============================================
    # YES / NO / BASIC
    # ============================================
    "yes": "Eego",
    "no": "Ngaaha",
    "maybe": "Kabaasa",
    "okay": "Kurungi",
    "ok": "Kurungi",
    "alright": "Kurungi",
    "sure": "Bwenkanya",
    "of course": "Bwenkanya",
    "i don't know": "Tinkumanya",
    "i know": "Ninkumanya",
    "i agree": "Ninkwikiriza",
    "i disagree": "Tinkwikiriza",
    "correct": "Nikyo",
    "wrong": "Kibi",
    "right": "Kurungi",
    "true": "Amazima",
    "false": "Ibi",

    # ============================================
    # QUESTION WORDS
    # ============================================
    "what": "Ki",
    "what is this": "Eki niki",
    "what is that": "Ekyo niki",
    "who": "Oha",
    "who are you": "Iwe oha",
    "where": "Nka",
    "where are you": "Ori nka",
    "where are you going": "Noori kugyenda nka",
    "when": "Ryari",
    "why": "Ahabw'enki",
    "how": "Ota",
    "how much": "Ngani",
    "how much is this": "Eki nikigura ssente ngani",
    "how many": "Ngani",
    "which": "Ki",
    "whose": "Wa oha",
    "what time is it": "Ssaawa ngani",

    # ============================================
    # PERSONAL PRONOUNS
    # ============================================
    "i": "Nye",
    "me": "Nye",
    "you": "Iwe",
    "he": "We",
    "she": "We",
    "it": "Kyo",
    "we": "Itwe",
    "us": "Itwe",
    "they": "Bo",
    "them": "Bo",
    "my": "Wanje",
    "your": "Wawe",
    "his": "We",
    "her": "We",
    "our": "Waitu",
    "their": "Waabo",
    "mine": "Kyange",
    "yours": "Kyawe",

    # ============================================
    # FAMILY
    # ============================================
    "man": "Omusaija",
    "woman": "Omukazi",
    "boy": "Omwojo",
    "girl": "Omwishiki",
    "child": "Omwana",
    "children": "Abaana",
    "baby": "Omwana omuto",
    "father": "Taata",
    "mother": "Maama",
    "son": "Omutabani",
    "daughter": "Omuhara",
    "brother": "Mukwano gw'omusaija",
    "sister": "Mukwano gw'omukazi",
    "family": "Amaka",
    "friend": "Munywani",
    "friends": "Banywani",
    "neighbor": "Omutaahi",
    "teacher": "Omwegyesa",
    "student": "Omwegyerwa",
    "doctor": "Omushaho",
    "nurse": "Omureezi",
    "police": "Poliisi",
    "soldier": "Omuserikare",
    "driver": "Omushoferi",
    "farmer": "Omuhiigi",
    "trader": "Omushubuzi",
    "customer": "Omuguzi",
    "guest": "Omugyenyi",
    "god": "Ruhanga",
    "lord": "Mukama",
    "king": "Omukama",
    "chief": "Omukuru",

    # ============================================
    # NUMBERS
    # ============================================
    "one": "Kimwe",
    "two": "Kibiri",
    "three": "Kishatu",
    "four": "Kina",
    "five": "Kitaano",
    "six": "Mukaaga",
    "seven": "Mushanju",
    "eight": "Munaana",
    "nine": "Mwenda",
    "ten": "Kumi",
    "eleven": "Kumi na kimwe",
    "twelve": "Kumi na kibiri",
    "twenty": "Makumi abiri",
    "thirty": "Makumi ashatu",
    "forty": "Makumi ana",
    "fifty": "Makumi ataano",
    "sixty": "Makumi mukaaga",
    "seventy": "Makumi mushanju",
    "eighty": "Makumi munaana",
    "ninety": "Makumi mwenda",
    "hundred": "Kikumi",
    "thousand": "Rukumi",
    "million": "Akakadde",

    # ============================================
    # TIME & DATES
    # ============================================
    "today": "Erizooba",
    "yesterday": "Nyomwabazyo",
    "tomorrow": "Nyenkyakare",
    "now": "Hatati",
    "later": "Anyima",
    "soon": "Vuba",
    "morning": "Omushana",
    "afternoon": "Eihwe",
    "evening": "Omugoroba",
    "night": "Ekiro",
    "day": "Eizooba",
    "week": "Eshumya",
    "month": "Omwezi",
    "year": "Omwaka",
    "hour": "Shaaha",
    "minute": "Edakiika",
    "second": "Sekendi",
    "monday": "Orwokubanza",
    "tuesday": "Orwakabiri",
    "wednesday": "Orwakashatu",
    "thursday": "Orwakana",
    "friday": "Orwakataano",
    "saturday": "Orwamukaaga",
    "sunday": "Sande",
    "time": "Obwire",
    "always": "Buriijo",
    "never": "Tikiri",
    "sometimes": "Amazima",
    "early": "Vuba",
    "late": "Ekyahingwire",

    # ============================================
    # FOOD & DRINK
    # ============================================
    "food": "Ebyokurya",
    "water": "Amaizi",
    "milk": "Amate",
    "tea": "Caayi",
    "coffee": "Kaawa",
    "juice": "Jusi",
    "soda": "Soda",
    "beer": "Byaari",
    "bread": "Omugaati",
    "rice": "Omucere",
    "beans": "Ebihimba",
    "meat": "Enyama",
    "chicken": "Enkoko",
    "beef": "Enyama y'ente",
    "goat": "Embuzi",
    "fish": "Ekyenyanja",
    "egg": "Eki",
    "eggs": "Amagi",
    "fruit": "Ekibazi",
    "banana": "Ekitookye",
    "matooke": "Ebitookye",
    "mango": "Omuyembe",
    "orange": "Omucungwa",
    "pineapple": "Anaasi",
    "avocado": "Ovakado",
    "tomato": "Enyanya",
    "onion": "Ekitunguru",
    "potato": "Kikoola",
    "cassava": "Muhogo",
    "maize": "Ekigusha",
    "salt": "Omunyu",
    "sugar": "Sukari",
    "oil": "Amafuta",
    "honey": "Obwoki",
    "breakfast": "Eky'omu maka",
    "lunch": "Eky'omushana",
    "dinner": "Eky'omugoroba",
    "hungry": "Enjara",
    "i am hungry": "Ndi n'enjara",
    "thirsty": "Enyota",
    "i am thirsty": "Ndi n'ennyota",
    "delicious": "Nikiija",
    "i want to eat": "Ninkunda kurya",

    # ============================================
    # BODY & HEALTH
    # ============================================
    "head": "Omutwe",
    "eye": "Eriisho",
    "eyes": "Amaisho",
    "ear": "Okutu",
    "nose": "Ennyindo",
    "mouth": "Omunwa",
    "tooth": "Eriino",
    "teeth": "Amaino",
    "tongue": "Orurimi",
    "neck": "Omukoshi",
    "shoulder": "Ekyega",
    "arm": "Omukono",
    "hand": "Omukono",
    "finger": "Orukumu",
    "chest": "Ekifuba",
    "stomach": "Enda",
    "back": "Omugongo",
    "leg": "Okuguru",
    "foot": "Ekyere",
    "heart": "Omutima",
    "blood": "Eshagama",
    "bone": "Egiimba",
    "skin": "Orushu",
    "hair": "Enywe",
    "sick": "Ndwire",
    "i am sick": "Ndwire",
    "pain": "Obwire",
    "hospital": "Edwaariro",
    "medicine": "Eshagama",
    "health": "Amagara",
    "life": "Amagara",
    "death": "Okufa",
    "tired": "Nkaaba",
    "i am tired": "Nkaaba",
    "sleep": "Oturo",
    "i want to sleep": "Ninkunda oturo",

    # ============================================
    # PLACES & DIRECTIONS
    # ============================================
    "home": "Omuka",
    "house": "Enju",
    "school": "Ishomero",
    "church": "Ekanisa",
    "market": "Akatare",
    "shop": "Aduuka",
    "bank": "Banka",
    "road": "Omuhanda",
    "street": "Omuhanda",
    "city": "Ekibuga",
    "village": "Ekyaaro",
    "country": "Ensi",
    "world": "Ensi",
    "place": "Ahantu",
    "here": "Hano",
    "there": "Hariya",
    "everywhere": "Buri hamwe",
    "near": "Hahi",
    "far": "Hara",
    "north": "Amajuru",
    "south": "Amajyepfo",
    "east": "Eihanga",
    "west": "Ibambangire",
    "up": "Iguru",
    "down": "Hansi",
    "inside": "Omunda",
    "outside": "Ahaawe",
    "where is the bathroom": "Enyumba y'omuyigo eri nka",
    "where is the market": "Akatare kari nka",
    "i am lost": "Ntaahire",
    "i am going home": "Ninkugyenda omuka",
    "i am going to the market": "Ninkugyenda omu katare",

    # ============================================
    # VERBS & ACTIONS
    # ============================================
    "go": "Gyenda",
    "come": "Ija",
    "eat": "Rya",
    "drink": "Nywa",
    "sleep": "Rara",
    "wake up": "Zaamuka",
    "walk": "Tambura",
    "run": "Irukanga",
    "sit": "Tuura",
    "stand": "Yemera",
    "see": "Reeba",
    "look": "Reeba",
    "hear": "Hurira",
    "listen": "Hurikiza",
    "speak": "Gamba",
    "talk": "Gamba",
    "say": "Gamba",
    "tell": "Teeriza",
    "ask": "Buuza",
    "answer": "Ddamu",
    "give": "Ha",
    "take": "Twara",
    "bring": "Reeta",
    "send": "Tuma",
    "buy": "Gura",
    "sell": "Guza",
    "pay": "Sasura",
    "work": "Kora",
    "play": "Zanya",
    "read": "Shoma",
    "write": "Handiika",
    "learn": "Iga",
    "teach": "Egyesa",
    "help": "Bara",
    "help me": "Mbabare",
    "wait": "Linda",
    "stop": "Yemera",
    "start": "Tandika",
    "finish": "Mariiriza",
    "open": "Kingura",
    "close": "Kinga",
    "enter": "Taaha",
    "exit": "Furuka",
    "know": "Manya",
    "understand": "Mutegyerereza",
    "i don't understand": "Tinkumanya",
    "think": "Teesheka",
    "want": "Kunda",
    "i want": "Ninkunda",
    "i don't want": "Tinkunda",
    "need": "Beetaaga",
    "love": "Kunda",
    "i love you": "Ninkukunda",
    "like": "Siima",
    "i like it": "Ninkisima",
    "hate": "Kyaara",
    "laugh": "Sheka",
    "cry": "Rira",
    "sing": "Zimba",
    "dance": "Zina",
    "pray": "Saba",

    # ============================================
    # ADJECTIVES
    # ============================================
    "good": "Kirungi",
    "very good": "Kirungi munonga",
    "bad": "Kibi",
    "very bad": "Kibi munonga",
    "big": "Kinene",
    "small": "Kito",
    "long": "Kirayi",
    "short": "Kito",
    "tall": "Murayi",
    "new": "Kipya",
    "old": "Kikuru",
    "young": "Muto",
    "hot": "Kyokya",
    "cold": "Kinyogoga",
    "warm": "Kyokya",
    "fast": "Vuba",
    "slow": "Gahoro",
    "easy": "Kyangu",
    "difficult": "Kizibu",
    "beautiful": "Murungi",
    "ugly": "Mubi",
    "rich": "Mugagga",
    "poor": "Muvaavu",
    "happy": "Mushemererwa",
    "sad": "Munakuwavu",
    "angry": "Musungu",
    "afraid": "Mutina",
    "strong": "Muzimu",
    "weak": "Munafu",
    "clean": "Murongoofu",
    "dirty": "Mukyafu",
    "full": "Mujwire",
    "empty": "Mwaliirire",
    "important": "Kikuru",
    "possible": "Kisoboka",
    "impossible": "Tikisoboka",

    # ============================================
    # COLORS
    # ============================================
    "color": "Rangi",
    "red": "Myufu",
    "blue": "Buruu",
    "green": "Kiragara",
    "yellow": "Kyenvu",
    "black": "Dira",
    "white": "Jeru",
    "orange": "Mucungwa",
    "brown": "Kikukusi",
    "pink": "Pinki",

    # ============================================
    # NATURE & ANIMALS
    # ============================================
    "tree": "Omuti",
    "flower": "Ekyuma",
    "grass": "Orubingo",
    "animal": "Enyamaishwa",
    "dog": "Embwa",
    "cat": "Kapa",
    "cow": "Ente",
    "goat": "Embuzi",
    "sheep": "Entaama",
    "pig": "Embizi",
    "chicken": "Enkoko",
    "bird": "Ekyinyonyi",
    "fish": "Ekyenyanja",
    "lion": "Empologoma",
    "elephant": "Enjojo",
    "snake": "Omusota",
    "insect": "Ekyinyonyi",
    "sun": "Eizooba",
    "moon": "Omwezi",
    "star": "Enyonyi",
    "sky": "Iguru",
    "rain": "Enkuba",
    "wind": "Embeho",
    "cloud": "Ekire",
    "fire": "Omuriro",
    "smoke": "Omwika",
    "weather": "Obwire",

    # ============================================
    # MISC COMMON WORDS
    # ============================================
    "name": "Iziina",
    "language": "Orurimi",
    "word": "Ekigambo",
    "book": "Ekitabo",
    "paper": "Orupapura",
    "pen": "Ekirimba",
    "phone": "Esima",
    "money": "Sente",
    "work": "Omurimo",
    "job": "Omurimo",
    "salary": "Empeera",
    "price": "Omuguzi",
    "cheap": "Kyangu",
    "expensive": "Bbei",
    "free": "Bwereere",
    "gift": "Ekirabo",
    "news": "Amawulire",
    "story": "Olugero",
    "song": "Orwimbo",
    "music": "Omuziki",
    "picture": "Ekifaananyi",
    "letter": "Ebaruha",
    "message": "Obubaka",
    "problem": "Kizibu",
    "question": "Ekibuuza",
    "answer": "Eky'okuddamu",
    "idea": "Ekirowoozo",
    "truth": "Amazima",
    "lie": "Obuhangazi",
    "love": "Okukunda",
    "peace": "Emirembe",
    "war": "Entaro",
}

def lookup_rukiga(text: str) -> str:
    """Look up English text in the Rukiga/Runyankole dictionary"""
    key = text.lower().strip().rstrip('!?.,;:')
    return RUKIGA_DICT.get(key)